# Generated by Django 3.0.1 on 2019-12-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('days_till_harvest', models.IntegerField(default=60)),
                ('planting_date', models.DateField(default='2020-01-01')),
            ],
        ),
    ]
