# Generated by Django 3.0.1 on 2019-12-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='calories',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_spacing',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(default='Vege', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='seeding_time',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='plant',
            name='yield_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(max_length=20),
        ),
    ]
